const express =require('express');
const bodyParser =require('body-parser');
const mongoose = require('mongoose');

// ADD MONGOOSE
mongoose.connect('mongodb+srv://john:feFbnxxOmq1B@cluster0.0gxdu.mongodb.net/test',
  { useNewUrlParser: true,
    useUnifiedTopology: true })
  .then(() => console.log('Connection to MongoDB successful !'))
  .catch(() => console.log('Connection to MongoDB failed !'));

const app = express();

const Sauce = require('./models/Sauce');

// ADD HEADERS
app.use((req, res, next) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content, Accept, Content-Type, Authorization');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
    next();
});

app.use(bodyParser.json());

// POST USER SAUCE
app.post ('/api/stuff', (req, res , next) => {
    // REMOVE STANDARD ID GENERATED BY MONGODB
    delete req.body._id;
    // ADD SCHEMA
    const sauce = new Sauce({
        ...req.body
    });
    // STORING TO MONGODB
    thing.save()
        .then(() => res.status(201).json({ message: 'Hot sauces added !'}))
        .catch(error => res.status(400).json({ error }));
});

// TEST MESSAGE
app.use((req, res, next) => {
    res.json({ message: 'Votre requète a bien été reçu !'});
});

module.exports = app;